### ISSUE TITLE
Which article does this method refer to?

### ISSUE THREAD

**Issue by xdheheda** [Obelus0/Green_Cover_Detection#1]
Hello, could you please tell me if you referred to that article? I want to learn it.

**Comment by Obelus0** [comment]
Which article?
Can you introduce yourself?

**Comment by xdheheda** [comment]
Maybe my previous statement was wrong.
I am a Chinese student at Nanjing University of Aeronautics and Astronautics, currently working on my PhD.
If possible, I would like to know which article your code is referring to, and if possible, I would like to study it and cite it in my paper.



At 2021-07-12 12:33:32, "Obelus0" ***@***.***> wrote:

Which article?
Can you introduce yourself?

**Comment by Obelus0** [comment]
https://towardsdatascience.com/color-identification-in-images-machine-learning-application-b26e770c4c71 some inspiration was taken from here and otherwise techniques used are opencv methods
